apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: agents.attestation.com
spec:
  group: attestation.com
  scope: Namespaced
  names:
    plural: agents
    singular: agent
    kind: Agent
    listKind: AgentList
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                agentName:
                  type: string
                nodeStatus:
                  type: string
                podStatus:
                  type: array
                  items:
                    type: object
                    properties:
                      podName:
                        type: string
                      tenantId:
                        type: string
                      status:
                        type: string
                      reason:
                        type: string
                      lastCheck:
                        type: string
                        format: date-time
                lastUpdate:
                  type: string
                  format: date-time
