apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name }}
  namespace: {{ .Values.namespace }}
type: {{ .Values.secret.type }}
data:
  attestation-secret-hmac: {{ .Values.secret.hmac | quote }}
  verifier-private-key: {{ .Values.secret.privateKey | quote }}
  verifier-public-key: {{ .Values.secret.publicKey | quote }}
