apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name }}
  namespace: {{ .Values.namespace }}
type: {{ .Values.secret.type }}
data:
  {{ .Values.secret.hmac.key }}: {{ .Values.secret.hmac.value | quote }}
  {{ .Values.secret.verifierPrivateKey.key }}: {{ .Values.secret.verifierPrivateKey.value | quote }}
  {{ .Values.secret.verifierPublicKey.key }}: {{ .Values.secret.verifierPublicKey.value | quote }}
