apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: attestationRequest.example.com
spec:
  group: example.com
  names:
    kind: AttestationRequest
    listKind: AttestationRequestList
    plural: attestationRequests
    singular: attestationRequest
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                podName:
                  type: string
                tenantID:
                  type: string
                agent:
                  type: string
                issued:
                  type: string
                  format: date-time
                hmac:
                  type: string
