---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: pod-handler-sa
  namespace: attestation-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pod-handler-role
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch", "create"]  # permission for pods
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["example.com"]  # Change this to your specific CRD group
    resources: ["agents"]  # Add your CRD resources here
    verbs: ["get", "list", "watch"]
  - apiGroups: ["example.com"]  # Change this to your specific CRD group
    resources: ["attestationrequests"]  # Add your CRD resources here
    verbs: ["get", "list", "watch", "create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: pod-handler-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: pod-handler-role
subjects:
  - kind: ServiceAccount
    name: pod-handler-sa
    namespace: attestation-system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pod-handler
  namespace: attestation-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pod-handler
  template:
    metadata:
      labels:
        app: pod-handler
    spec:
      containers:
        - name: pod-handler
          image: franczar/k8s-attestation-pod-handler:latest
          env:
            - name: REGISTRAR_HOST
              value: "192.168.0.103"
            - name: REGISTRAR_PORT
              value: "30000"
            - name: POD_HANDLER_PORT
              value: "8080"
            - name: ATTESTATION_SECRET
              valueFrom:
                secretKeyRef:
                  name: attestation-secrets
                  key: attestation-secret-hmac              
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: kube-config
              mountPath: /root/.kube
      volumes:
        - name: kube-config
          hostPath:
            path: /home/node/.kube
      nodeSelector:
        node-role.kubernetes.io/control-plane: "true"
      serviceAccountName: pod-handler-sa  # Assign ServiceAccount to pod-handler
---
apiVersion: v1
kind: Service
metadata:
  name: pod-handler-service
  namespace: attestation-system
spec:
  selector:
    app: pod-handler
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8080
      nodePort: 30001
  type: NodePort
