---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: pod-watcher-sa
  namespace: attestation-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pod-watcher-role
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["example.com"]  # Change this to your specific CRD group
    resources: ["agents"]  # Add your CRD resources here
    verbs: ["get", "list", "watch", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: pod-watcher-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: pod-watcher-role
subjects:
  - kind: ServiceAccount
    name: pod-watcher-sa
    namespace: attestation-system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pod-watcher
  namespace: attestation-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pod-watcher
  template:
    metadata:
      labels:
        app: pod-watcher
    spec:
      containers:
        - name: pod-watcher
          image: franczar/k8s-attestation-pod-watcher:latest
          volumeMounts:
            - name: kube-config
              mountPath: /root/.kube
      volumes:
        - name: kube-config
          hostPath:
            path: /home/node/.kube
      nodeSelector:
        node-role.kubernetes.io/control-plane: "true"
      serviceAccountName: pod-watcher-sa  # Using the ServiceAccount
