apiVersion: apps/v1
kind: Deployment
metadata:
  name: registrar
  namespace: attestation-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: registrar
  template:
    metadata:
      labels:
        app: registrar
    spec:
      containers:
        - name: registrar
          image: franczar/k8s-attestation-registrar:latest
          env:
            - name: REGISTRAR_PORT
              value: "8080"
          ports:
            - containerPort: 8080
      nodeSelector:
        node-role.kubernetes.io/control-plane: "true"
---
apiVersion: v1
kind: Service
metadata:
  name: registrar-service
  namespace: attestation-system
spec:
  selector:
    app: registrar
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30000
  type: NodePort
